item {
    id: 1
    name: 'Car'
}

item {
    id: 2
    name: 'Van'
}

item {
    id: 3
    name: 'Pedestrian'
}

item {
    id: 4
    name: 'Cyclist'
}

item {
    id: 5
    name: 
}

item {
    id: 6
    name: 
}

item {
    id: 7
    name: 'Truck'
}

item {
    id: 8
    name: 'Misc'
}
